// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCZBnvALT0xgWCYaxPkISJME8KSlh2vU',
    appId: '1:418660952228:web:51ff0bd3987b4b6fcb9e31',
    messagingSenderId: '418660952228',
    projectId: 'mobile-store-1f5c0',
    authDomain: 'mobile-store-1f5c0.firebaseapp.com',
    storageBucket: 'mobile-store-1f5c0.appspot.com',
    measurementId: 'G-2T9QR42XYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiGj5x9jMPK-GOn3dfGokLmvyA4z2wfDU',
    appId: '1:418660952228:android:05d185ded5e4e831cb9e31',
    messagingSenderId: '418660952228',
    projectId: 'mobile-store-1f5c0',
    storageBucket: 'mobile-store-1f5c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPvbR-RetQF55h668STRkXKUd2KC4AzL4',
    appId: '1:418660952228:ios:f8b2ad19442575fecb9e31',
    messagingSenderId: '418660952228',
    projectId: 'mobile-store-1f5c0',
    storageBucket: 'mobile-store-1f5c0.appspot.com',
    iosClientId: '418660952228-9u1fnbhbc622k60e50jgrbihipntdmbs.apps.googleusercontent.com',
    iosBundleId: 'com.example.elkhwagaStor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPvbR-RetQF55h668STRkXKUd2KC4AzL4',
    appId: '1:418660952228:ios:be3e496ee45bf360cb9e31',
    messagingSenderId: '418660952228',
    projectId: 'mobile-store-1f5c0',
    storageBucket: 'mobile-store-1f5c0.appspot.com',
    iosClientId: '418660952228-p7n0sr890lqs4iptock9k3ui753povl9.apps.googleusercontent.com',
    iosBundleId: 'com.example.elkhwagaStor.RunnerTests',
  );
}
